-- Test data initialization

DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT (ID LONG PRIMARY KEY AUTO_INCREMENT NOT NULL,
                      CATEGORY VARCHAR(30) NOT NULL,
                      NAME VARCHAR(30) NOT NULL,
                      DESCRIPTION VARCHAR(30) NOT NULL,
                      UNITPRICE DECIMAL(19,4) NOT NULL,
                      INVENTORY VARCHAR(10) NOT NULL,
                      PAYMENT_OPTIONS VARCHAR(30) NOT NULL,
                      DELIVERY_OPTIONS VARCHAR(30) NOT NULL);

CREATE UNIQUE INDEX idx_acc on PRODUCT(ID,NAME);

INSERT INTO PRODUCT (ID, CATEGORY, NAME, DESCRIPTION, UNITPRICE, INVENTORY, PAYMENT_OPTIONS, DELIVERY_OPTIONS)
VALUES (101,'ELECTRONICS','TV','LG Smart TV',1000.0000,20,'DIRECT','X');

INSERT INTO PRODUCT (ID, CATEGORY, NAME, DESCRIPTION, UNITPRICE, INVENTORY, PAYMENT_OPTIONS, DELIVERY_OPTIONS)
VALUES (102,'FASHION','Skirt 101','Black Skirt',20.0000,10,'INSTALLMENT','X');

INSERT INTO PRODUCT (ID, CATEGORY, NAME, DESCRIPTION, UNITPRICE, INVENTORY, PAYMENT_OPTIONS, DELIVERY_OPTIONS)
VALUES (103,'FOOD','Bread','Whole Wheat Bread',5,5,'DIRECT','X');
